### ISSUE TITLE
Need a way to get notified on activator shutdown (for pax-web unregistration)

### ISSUE THREAD

**Issue by steinarb** [sbang/jsr330activator#2]
When the activator is shut down there is no notification sent to the injection points.

It is necessary to have some form of notification of the shutdown to implement pax-web configuration-by-code semantics:
 https://github.com/ops4j/org.ops4j.pax.web/blob/master/samples/helloworld-wc/src/main/java/org/ops4j/pax/web/samples/helloworld/wc/internal/Activator.java#L183

**Comment by sbang** [comment]
I can think of two possible solutions:

1. The quick-and-dirty solution of retracting the injected services when releasing the injected services. This has three downsides:
    1. It's impossible to distinguish from an actual service retraction (which also should be handled)
    2. The retraction of the injected service will happen in an undefined order and this may not be right for an orderly cleanup (ie. the service needed to do a propert cleanup may already be retracted)
    3. This will only work for injections with property setters, not for injected fields
2. Create a new annotation @Shutdown that can be used to mark a method in the provider that should be called when the activator is stopped
