### ISSUE TITLE
jsr330activator only supports a single provider for each type

### ISSUE THREAD

**Issue by steinarb** [sbang/jsr330activator#9]
If two or more providers exists for a single type (e.g. two providers for the Servlet service), only one is picked up and exposed as an OSGi service.

This is a serious limitation for webservice bundles using the pax web whiteboard extender, where there may be a desire to expose multiple servlet bundles to be picked up by the whiteboard extender.

**Comment by sbang** [comment]
Issue fixed by commit d83dd814eedfbfed97a2aa1f1fb5a80778385092.

Closing the issue.
